export default function () {
  const mat = [
    "PLA",
    "PLA Matte",
    "PLA Metal",
    "PLA-CF",
    "PETG",
    "PETG Translucent",
    "PETG-HF",
    "PETG-CF",
    "ABS",
    "Flexibel TPU/TPE",
    "Nylon (PA)",
    "Carbonfaser",
    "ASA",
    "PLA Max",
    "PLA Silk",
    "PVA/BVOH/BreakAway",
    "Glasfaser",
    "PVB",
    "Flexible",
    "PETG Max",
    "PC",
    "PP",
    "PC-ABS",
    "Wood",
    "PPS",
    "PC-FR",
  ];
  return mat;
}
